Ansible Workshop @ PyCon 2015
=============================

== Description of the workshop ==
Ansible is an IT automation tool that can be used to configure, deploy and orchestrate many different Infrastructure based tasks. Ansible can be used for system configuration, software deployment, application or infrastructure orchestration, more importantly it is agent less and no master/slave configuration required for it. It uses yml to write playbook which is readable and easy to manageable, did I not mention it's comes with batteries included.

This workshop aims to hands-on upon the following topics:

* Ansible Basics
* Inventory
* Modules
* Playbook
* Variable
* Condition Handling
* Adhoc run
* System Configuration
* Application Orchestration
* Cloud Infra management (Docker, openstack, AWS)
* Creating custom modules
* Ansible Vault

=== Ansible Basics ===
Topics covered:

* What is Ansible?
* Why do we need it?
* What are the advantages of using it?
* How to configure Ansible?
* How to run adhoc commands?

=== Ansible Inventory ===
Topics covered:

* What is inventory file?
* What do we create an inventory file?
* How do we define groups of hosts for running Ansible?
* Explain the Ansible inventory file below
----
[www]
web1.myorg.com
web2.myorg.com
[db]
db1.myorg.com
[mail]
db1.myorg.com
----

=== Ansible Modules ===
Topics covered:

* What is ansible module library?
* How to use module for ansible ad-hoc commands?
* How to use module to ansible playbooks?
* How to get document of a module in ansible?
----
[Ad-hoc use case]
ansible webservers -m service -a "name=httpd state=started"

[Playbook use case]
- name: reboot the servers
  command: /sbin/reboot -t now

[Module document]
ansible-doc yum
----

=== Ansible Playbooks ===
Topics covered:

* Why should playbook instead of ad-hoc commands?
* How to write a playbook?
* What is User/Hosts and roles in playbook?
* How to use tag in playbook?
* How to execute a playbook?
----
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
    remote_user: root
    tasks:
        - name: ensure apache is at the latest version
          yum:
            pkg: httpd
            state: latest
----

=== Variables ===
Topics covered:

* What makes a valid variable name?
* How to define variable in playbook?
* How to define variable in inventory?
* What are registered variables?
* How to access complex variable data?
* Magic variables to get data about other hosts.
* How to pass a variable from command line?
* Variable precedence.
----
- hosts: webservers
  vars:
      http_port: 80

My amp goes to {{ variable_in_jinja_template }}

ansible hostname -m setup

ansible-playbook release.yml --extra-vars "version=1.23.45 other_variable=foo"
----

=== Condition Handling ===
Topics covered:

* How to handle different condition in ansible playbook?
* How to use register variable to apply a condition?
* How to apply condition for a specific role?
----
- include: tasks/sometasks.yml
  when: "'reticulating splines' in output"

tasks:
    - command: echo {{ item }}
      with_items: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5
----

=== Ad-hoc Run ===
Topics covered:

* Why would you use ad-hoc tasks versus playbooks?
* Parallelism and Shell Commands using ansible ad-hoc.
* Usecase of ad-hoc commands. like file-transfer, managing services etc.
----
ansible webservers -m service -a "name=httpd state=restarted"
ansible webservers -m git -a "repo=git://foo.example.org/repo.git dest=/srv/myapp version=HEAD"
ansible all -m user -a "name=foo state=absent"
----

=== Ansible Vault ===
Topics Covered:

* How to create and edit encryted files?
* How and why to rekey encrypted file?
* Running a plybook with Ansible vault

=== System Configuration ===
Topics covered:

* Overview about sytem modules provide by ansible.
* How to make sure system configuration always sane.
* Firewalld, SELinux configuration for a target server.
----
- selinux: policy=targeted state=enforcing
----

=== Application Orchestration ===
Topics covered:

* Delegation and rolling update
* Local Actions
----
- name: test play
  hosts: websevers
  serial: "30%"

- hosts: 127.0.0.1
  connection: local
----
